name: glass_morph
description: Animated glass-morphism widgets for Flutter.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0

flutter:
  uses-material-design: true
