name: glass_morph_widgets
description: A pure-Dart Flutter package providing animated glass-morphism widgets with zero native code. Supports mobile, web, and desktop platforms.
version: 1.1.0
homepage: https://liv-coder.github.io/glass_morph_widgets
repository: https://github.com/Liv-Coder/glass_morph_widgets
documentation: https://github.com/Liv-Coder/glass_morph_widgets
issue_tracker: https://github.com/Liv-Coder/glass_morph_widgets/issues
topics:
  - ui
  - widgets
  - glassmorphism
  - animation
  - flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0

flutter:
  uses-material-design: true
